name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v1
    - name: Extract Signature
      run: echo ${{secrets.KEY_FILE}} | base64 -d > $HOME/.android.jks
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup GoLang
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Build with Gradle
      run: ./gradlew assembleRelease
      env:
        KEY_PASS: ${{secrets.KEY_PASS}}
    - name: Publish Release APK
      uses: siristechnology/action-create-release@master
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_ACCESS_TOKEN}}
       RELEASE_FILE_PATH: app/build/outputs/apk/release/app-release.apk
       RELEASE_TITLE: "New Build"
      if: github.event.created
